### ISSUE TITLE
Not everyone uses a Debian-based distro

### ISSUE THREAD

**Issue by llunariis** [OSMANiCTeam/SimpleWebCloner#3]
https://github.com/OSMANiCTeam/SimpleWebCloner/blob/9449c15f24f78a6f4310589065389f9f95a84400/SimpleWebCloner.sh#L24

**Comment by JoshAtticus** [comment]
I can't be bothered to add OS detection, go make a PR if you want.

**Comment by theycallhermax** [comment]
no
